# Generated by Django 3.2.9 on 2021-11-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('pollution_level_00', models.DecimalField(decimal_places=1, max_digits=10)),
                ('pollution_level_01', models.DecimalField(decimal_places=1, max_digits=10)),
                ('pollution_level_02', models.DecimalField(decimal_places=1, max_digits=10)),
                ('industries', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('count_pesticide', models.IntegerField()),
                ('name_pesticide', models.CharField(max_length=250)),
                ('name_banned_pesticide', models.CharField(max_length=250)),
            ],
        ),
    ]
