# Generated by Django 3.2.9 on 2022-01-30 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Год иследевоние',
                'verbose_name_plural': 'Годы иследевония',
            },
        ),
        migrations.CreateModel(
            name='FormPreparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Форма препарата',
                'verbose_name_plural': 'Формы препаратов',
            },
        ),
        migrations.CreateModel(
            name='ImportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
            },
        ),
        migrations.CreateModel(
            name='StorageStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Состояние хранилища',
                'verbose_name_plural': 'Состояние хранилищ',
            },
        ),
        migrations.CreateModel(
            name='TypeContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Тип контейнера',
                'verbose_name_plural': 'Тип контейнера',
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255, verbose_name='Месторасположение хранилище')),
                ('name', models.CharField(max_length=255, verbose_name='Название хранилища')),
                ('add_info', models.CharField(max_length=255, null=True, verbose_name='Дополнительная информация')),
                ('obsolete_pesticides', models.CharField(max_length=255, null=True, verbose_name='Устаревшие пестициды, кг')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.region', verbose_name='Регион')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.storagestatus', verbose_name='Состояние хранилища')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.analysis', verbose_name='Год')),
            ],
            options={
                'verbose_name': 'Хранилища',
                'verbose_name_plural': 'Хранилищи',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_rooms', models.IntegerField(verbose_name='Количество складских помещений')),
                ('number_un_rooms', models.IntegerField(verbose_name='Количество складских помещений без загрязнения')),
                ('number_limit_pdk', models.IntegerField(verbose_name='Количество территории, где количество пестицидов в пределах ПДК')),
                ('number_above_pdk', models.IntegerField(verbose_name='Количество территории, где количество пестицидов выше ПДК')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Помещения',
                'verbose_name_plural': 'Помещений',
            },
        ),
        migrations.CreateModel(
            name='Preparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название препарата')),
                ('location', models.CharField(max_length=255, verbose_name='Месторасположение хранилища')),
                ('name_location', models.CharField(max_length=255, verbose_name='Название хранилища')),
                ('trade_name', models.CharField(max_length=255, null=True, verbose_name='Торговое название')),
                ('number', models.IntegerField(verbose_name='Количество')),
                ('import_year', models.CharField(max_length=255, null=True, verbose_name='Год ввоза')),
                ('birth', models.CharField(max_length=255, null=True, verbose_name='Происхождение')),
                ('add_info', models.CharField(max_length=255, null=True, verbose_name='Дополнительная информация')),
                ('note', models.CharField(max_length=255, null=True, verbose_name='Замечания')),
                ('form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.formpreparation', verbose_name='Препаративная форма')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.region', verbose_name='Регион')),
                ('status_container', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preparation_statuses', to='main.typecontainer', verbose_name='Состояние контейнера')),
                ('type_container', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preparation_types', to='main.typecontainer', verbose_name='Тип контейнера')),
            ],
            options={
                'verbose_name': 'Препарат',
                'verbose_name_plural': 'Препараты',
            },
        ),
        migrations.CreateModel(
            name='Pesticide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255, verbose_name='Место  расположение')),
                ('count_pesticide', models.IntegerField(verbose_name='Кол-во пестицидов, кг')),
                ('name_pesticide', models.CharField(blank=True, max_length=250, null=True, verbose_name='Наименование пестицидов')),
                ('name_banned_pesticide', models.CharField(blank=True, max_length=250, null=True, verbose_name='Наименование запрещенных пестицидов')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Пестицид',
                'verbose_name_plural': 'Пестициды',
            },
        ),
    ]
