# Generated by Django 3.2.9 on 2021-11-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_importrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='name_banned_pesticide',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='name_pesticide',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
