# Generated by Django 3.2.9 on 2021-11-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_importrecord_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
