# Generated by Django 3.2.9 on 2022-01-23 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211118_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CommonPesticide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=255)),
                ('count_pesticide', models.IntegerField()),
                ('name_pesticide', models.CharField(blank=True, max_length=250, null=True)),
                ('name_banned_pesticide', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormPreparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Preparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('name_location', models.CharField(max_length=255)),
                ('trade_name', models.CharField(max_length=255, null=True)),
                ('number', models.IntegerField()),
                ('import_year', models.CharField(max_length=10, null=True)),
                ('birth', models.CharField(max_length=255, null=True)),
                ('add_info', models.CharField(max_length=255, null=True)),
                ('note', models.CharField(max_length=255, null=True)),
                ('form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.formpreparation')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Soil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_rooms', models.IntegerField()),
                ('number_un_rooms', models.IntegerField()),
                ('number_limit_pdk', models.IntegerField()),
                ('number_above_pdk', models.IntegerField()),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.region')),
            ],
        ),
        migrations.CreateModel(
            name='StorageRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('add_info', models.CharField(max_length=255, null=True)),
                ('obsolete_pesticides', models.CharField(max_length=255, null=True)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.region')),
            ],
        ),
        migrations.CreateModel(
            name='StorageRoomsStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TypeContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.AddField(
            model_name='storagerooms',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.storageroomsstatus'),
        ),
        migrations.AddField(
            model_name='storagerooms',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.analysis'),
        ),
        migrations.AddField(
            model_name='preparation',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.region'),
        ),
        migrations.AddField(
            model_name='preparation',
            name='status_container',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preparation_statuses', to='main.typecontainer'),
        ),
        migrations.AddField(
            model_name='preparation',
            name='type_container',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preparation_types', to='main.typecontainer'),
        ),
        migrations.AddField(
            model_name='commonpesticide',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.region'),
        ),
    ]
