# Generated by Django 3.2.9 on 2022-01-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20220123_1138'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommonPesticide',
            new_name='Pesticide',
        ),
        migrations.RenameModel(
            old_name='Soil',
            new_name='Room',
        ),
        migrations.RenameModel(
            old_name='StorageRooms',
            new_name='Storage',
        ),
        migrations.RenameModel(
            old_name='StorageRoomsStatus',
            new_name='StorageStatus',
        ),
        migrations.AlterModelOptions(
            name='analysis',
            options={'verbose_name': 'Год иследевоние', 'verbose_name_plural': 'Годы иследевония'},
        ),
        migrations.AlterModelOptions(
            name='formpreparation',
            options={'verbose_name': 'Форма препарата', 'verbose_name_plural': 'Формы препаратов'},
        ),
        migrations.AlterModelOptions(
            name='pesticide',
            options={'verbose_name': 'Пестицид', 'verbose_name_plural': 'Пестициды'},
        ),
        migrations.AlterModelOptions(
            name='preparation',
            options={'verbose_name': 'Препарат', 'verbose_name_plural': 'Препараты'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Район', 'verbose_name_plural': 'Районы'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Помещения', 'verbose_name_plural': 'Помещений'},
        ),
        migrations.AlterModelOptions(
            name='storage',
            options={'verbose_name': 'Хранилища', 'verbose_name_plural': 'Хранилищи'},
        ),
        migrations.AlterModelOptions(
            name='storagestatus',
            options={'verbose_name': 'Состояние хранилища', 'verbose_name_plural': 'Состояние хранилищ'},
        ),
        migrations.AlterModelOptions(
            name='typecontainer',
            options={'verbose_name': 'Тип контейнера', 'verbose_name_plural': 'Тип контейнера'},
        ),
        migrations.AddField(
            model_name='preparation',
            name='name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
